require 'erb'

task :default do
  puts "compiling erb..."

	Dir['*'].each do |file|
		if file =~ /erb$/
			File.open file.sub(/\.erb/, ''), 'w' do |new_file|
				new_file.write(
					ERB.new(File.read(file))
					.result(binding)
					.gsub(/'(.)'/){$1.ord} # add '' char support`
				)
			end
		end
	end

	puts "compiling jack"
	puts `compile.cmd` # god, what a stupid hack
end

# stupid directory watcher didn't work,
# so we're just gonna rebuild every few seconds
task :watch do 
	while true
		Rake::Task[:default].reenable
		Rake::Task[:default].invoke
		sleep 10
	end
end


